### ISSUE TITLE
Zombies not Spawning A19.3 Stable

### ISSUE THREAD

**Issue by Motive313** [ZehMatt/7dtd-WalkerSim#2]
Error:
MissingMethodException: void EntityAlive.SetInvestigatePosition(UnityEngine.Vector3,int)

When the server tries to spawn a zombie that is activated by a player.

**Comment by ZehMatt** [comment]
I'm working on a update since a while, it should be fixed with the next release that I have planned, I can not tell a specific date right now. I might just release a hot fix for this, not sure yet but thanks for the report.

**Comment by Xtry333** [comment]
Hello, how is the progress on this bug? 
It effectively blocks usage of this mod, because no zombies are spawning. Hotfix for this one would be awesome.
Thank you.

**Comment by ZehMatt** [comment]
Released the new update.
